version: "3.4"
services:
  # Postgres DB
  db:
    image: postgres:12
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: dosco/graphjin:latest
    environment:
      GO_ENV: "development"
    volumes:
      - ./config:/config
    ports:
      - "9071:9071"
    depends_on:
      - db

volumes:
  db_data:
